<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Provisioning_API\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\Provisioning_API\\BackgroundJob\\CheckExpiredSubscriptions' => $baseDir . '/../lib/BackgroundJob/CheckExpiredSubscriptions.php',
    'OCA\\Provisioning_API\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Provisioning_API\\Controller\\AUserDataOCSController' => $baseDir . '/../lib/Controller/AUserDataOCSController.php',
    'OCA\\Provisioning_API\\Controller\\AppConfigController' => $baseDir . '/../lib/Controller/AppConfigController.php',
    'OCA\\Provisioning_API\\Controller\\AppsController' => $baseDir . '/../lib/Controller/AppsController.php',
    'OCA\\Provisioning_API\\Controller\\GroupsController' => $baseDir . '/../lib/Controller/GroupsController.php',
    'OCA\\Provisioning_API\\Controller\\PlansController' => $baseDir . '/../lib/Controller/PlansController.php',
    'OCA\\Provisioning_API\\Controller\\PreferencesController' => $baseDir . '/../lib/Controller/PreferencesController.php',
    'OCA\\Provisioning_API\\Controller\\UsersController' => $baseDir . '/../lib/Controller/UsersController.php',
    'OCA\\Provisioning_API\\Controller\\VerificationController' => $baseDir . '/../lib/Controller/VerificationController.php',
    'OCA\\Provisioning_API\\Db\\Organization' => $baseDir . '/../lib/Db/Organization.php',
    'OCA\\Provisioning_API\\Db\\OrganizationMapper' => $baseDir . '/../lib/Db/OrganizationMapper.php',
    'OCA\\Provisioning_API\\Db\\Plan' => $baseDir . '/../lib/Db/Plan.php',
    'OCA\\Provisioning_API\\Db\\PlanMapper' => $baseDir . '/../lib/Db/PlanMapper.php',
    'OCA\\Provisioning_API\\Db\\Subscription' => $baseDir . '/../lib/Db/Subscription.php',
    'OCA\\Provisioning_API\\Db\\SubscriptionHistory' => $baseDir . '/../lib/Db/SubscriptionHistory.php',
    'OCA\\Provisioning_API\\Db\\SubscriptionHistoryMapper' => $baseDir . '/../lib/Db/SubscriptionHistoryMapper.php',
    'OCA\\Provisioning_API\\Db\\SubscriptionMapper' => $baseDir . '/../lib/Db/SubscriptionMapper.php',
    'OCA\\Provisioning_API\\FederatedShareProviderFactory' => $baseDir . '/../lib/FederatedShareProviderFactory.php',
    'OCA\\Provisioning_API\\Listener\\UserDeletedListener' => $baseDir . '/../lib/Listener/UserDeletedListener.php',
    'OCA\\Provisioning_API\\Middleware\\Exceptions\\NotSubAdminException' => $baseDir . '/../lib/Middleware/Exceptions/NotSubAdminException.php',
    'OCA\\Provisioning_API\\Middleware\\ProvisioningApiMiddleware' => $baseDir . '/../lib/Middleware/ProvisioningApiMiddleware.php',
    'OCA\\Provisioning_API\\Middleware\\SubscriptionMiddleware' => $baseDir . '/../lib/Middleware/SubscriptionMiddleware.php',
    'OCA\\Provisioning_API\\ResponseDefinitions' => $baseDir . '/../lib/ResponseDefinitions.php',
    'OCA\\Provisioning_API\\Service\\OrganizationService' => $baseDir . '/../lib/Service/OrganizationService.php',
    'OCA\\Provisioning_API\\Service\\PlanService' => $baseDir . '/../lib/Service/PlanService.php',
    'OCA\\Provisioning_API\\Service\\SubscriptionService' => $baseDir . '/../lib/Service/SubscriptionService.php',
);
